import React from 'react';
import { Link } from 'react-router-dom';
import AppLayout from '../../components/layout/AppLayout';
import { FileText, Download, Shield, TrendingUp, AlertTriangle, CheckCircle2 } from 'lucide-react';
import { useToast } from '../../context/ToastContext';
import reportsData from '../../data/reports.json';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';

export default function Reports() {
  const { showToast } = useToast();
  const { trialReport } = reportsData;

  const comparisonData = [
    { metric: 'SA-Specific Threats', mcafee: 16, shieldai: 47 },
    { metric: 'Phishing Kits Blocked', mcafee: 3, shieldai: 19 },
    { metric: 'Ransomware Stopped', mcafee: 0, shieldai: 6 },
  ];

  const topThreatsData = trialReport.topThreats.map(t => ({
    name: t.name,
    count: t.count,
    fill: t.severity === 'critical' ? '#EF4444' : t.severity === 'high' ? '#F59E0B' : '#FBBF24',
  }));

  const CustomTooltip = ({ active, payload }: any) => {
    if (active && payload && payload.length) {
      return (
        <div className="bg-navy-700 border border-gray-600 rounded-lg p-3 shadow-xl">
          <p className="text-sm text-gray-100">{payload[0].payload.metric}</p>
          <p className="text-sm text-red-400">
            McAfee: <span className="font-semibold">{payload[0].value}</span>
          </p>
          <p className="text-sm text-green-400">
            ShieldAI: <span className="font-semibold">{payload[1].value}</span>
          </p>
        </div>
      );
    }
    return null;
  };

  const handleDownloadPDF = () => {
    showToast('PDF export available in Growth plan', 'info');
  };

  return (
    <AppLayout title="Reports">
      <div className="space-y-6">
        {/* Page Header */}
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-2xl font-display font-bold text-white mb-2">Security Assessment Report</h2>
            <p className="text-gray-400">Comprehensive analysis of your protection during the trial period</p>
          </div>
          <button
            onClick={handleDownloadPDF}
            className="flex items-center gap-2 px-4 py-2 bg-shield-blue hover:bg-shield-electric text-white rounded-lg transition-all"
          >
            <Download className="h-4 w-4" />
            Export PDF
          </button>
        </div>

        {/* Trial Report Card */}
        <div className="bg-gradient-to-br from-navy-700 to-navy-600 border border-gray-600/50 rounded-xl overflow-hidden shadow-2xl">
          {/* Report Header */}
          <div className="bg-navy-600 border-b border-gray-600/50 px-8 py-6">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-4">
                <div className="p-3 bg-shield-blue/20 rounded-lg">
                  <Shield className="h-8 w-8 text-shield-blue" />
                </div>
                <div>
                  <h3 className="text-xl font-semibold text-white">Security Assessment Report</h3>
                  <p className="text-sm text-gray-400">Generated by ShieldAI Edge Agent v1.2.4</p>
                </div>
              </div>
              <div className="text-right">
                <p className="text-sm text-gray-400">Period</p>
                <p className="text-white font-medium">{trialReport.period}</p>
              </div>
            </div>
          </div>

          {/* Report Body */}
          <div className="p-8 space-y-8">
            {/* Company Info */}
            <div>
              <p className="text-sm text-gray-400 mb-1">Company</p>
              <p className="text-2xl font-bold text-white">{trialReport.company}</p>
            </div>

            {/* Key Metrics */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
              <div className="bg-navy-700/50 border border-gray-600/30 rounded-lg p-5">
                <div className="flex items-center gap-2 mb-2">
                  <Shield className="h-5 w-5 text-blue-400" />
                  <p className="text-sm text-gray-400">Total Threats</p>
                </div>
                <p className="text-3xl font-bold text-white">{trialReport.totalThreats}</p>
                <p className="text-xs text-gray-500 mt-1">Detected & Blocked</p>
              </div>

              <div className="bg-red-500/10 border border-red-500/30 rounded-lg p-5">
                <div className="flex items-center gap-2 mb-2">
                  <AlertTriangle className="h-5 w-5 text-red-400" />
                  <p className="text-sm text-gray-400">Missed by {trialReport.currentAVName.split(' ')[0]}</p>
                </div>
                <p className="text-3xl font-bold text-red-400">{trialReport.threatsMissedByCurrentAV}</p>
                <p className="text-xs text-gray-500 mt-1">Would have been breached</p>
              </div>

              <div className="bg-amber-500/10 border border-amber-500/30 rounded-lg p-5">
                <div className="flex items-center gap-2 mb-2">
                  <AlertTriangle className="h-5 w-5 text-amber-400" />
                  <p className="text-sm text-gray-400">Critical Incidents</p>
                </div>
                <p className="text-3xl font-bold text-amber-400">{trialReport.criticalIncidents}</p>
                <p className="text-xs text-gray-500 mt-1">High-risk threats</p>
              </div>

              <div className="bg-green-500/10 border border-green-500/30 rounded-lg p-5">
                <div className="flex items-center gap-2 mb-2">
                  <TrendingUp className="h-5 w-5 text-green-400" />
                  <p className="text-sm text-gray-400">Damage Avoided</p>
                </div>
                <p className="text-3xl font-bold text-green-400">{trialReport.estimatedDamageAvoided}</p>
                <p className="text-xs text-gray-500 mt-1">Estimated savings</p>
              </div>
            </div>

            {/* SA-Specific Threats Callout */}
            <div className="bg-shield-blue/10 border border-shield-blue/30 rounded-lg p-6">
              <div className="flex items-start gap-4">
                <div className="p-2 bg-shield-blue/20 rounded-lg">
                  <Shield className="h-6 w-6 text-shield-blue" />
                </div>
                <div className="flex-1">
                  <h4 className="text-lg font-semibold text-white mb-2">
                    African-Specific Threat Protection
                  </h4>
                  <p className="text-gray-300 mb-3">
                    <span className="text-2xl font-bold text-shield-blue">{trialReport.africanSpecificThreats}</span> of{' '}
                    {trialReport.totalThreats} threats ({Math.round((trialReport.africanSpecificThreats / trialReport.totalThreats) * 100)}%)
                    were SA-specific attacks that global security tools often miss.
                  </p>
                  <p className="text-sm text-gray-400">
                    These include ABSA phishing kits, FNB spoofs, Eskom ransomware lures, and SARS scams — threats
                    specifically targeting South African businesses.
                  </p>
                </div>
              </div>
            </div>

            {/* Comparison Table */}
            <div>
              <h4 className="text-lg font-semibold text-white mb-4">ShieldAI vs Your Current Tool</h4>
              <div className="bg-navy-700/50 border border-gray-600/30 rounded-lg overflow-hidden">
                <table className="w-full">
                  <thead className="bg-navy-600 border-b border-gray-600">
                    <tr>
                      <th className="px-6 py-3 text-left text-sm font-medium text-gray-400">Metric</th>
                      <th className="px-6 py-3 text-center text-sm font-medium text-red-400">
                        {trialReport.currentAVName}
                      </th>
                      <th className="px-6 py-3 text-center text-sm font-medium text-green-400">ShieldAI</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-700/50">
                    <tr>
                      <td className="px-6 py-4 text-sm text-gray-300">SA-Specific Threats Detected</td>
                      <td className="px-6 py-4 text-center text-lg font-semibold text-red-400">16</td>
                      <td className="px-6 py-4 text-center text-lg font-semibold text-green-400">47</td>
                    </tr>
                    <tr>
                      <td className="px-6 py-4 text-sm text-gray-300">Phishing Kits Blocked</td>
                      <td className="px-6 py-4 text-center text-lg font-semibold text-red-400">3</td>
                      <td className="px-6 py-4 text-center text-lg font-semibold text-green-400">19</td>
                    </tr>
                    <tr>
                      <td className="px-6 py-4 text-sm text-gray-300">Ransomware Stopped</td>
                      <td className="px-6 py-4 text-center text-lg font-semibold text-red-400">0</td>
                      <td className="px-6 py-4 text-center text-lg font-semibold text-green-400">6</td>
                    </tr>
                    <tr>
                      <td className="px-6 py-4 text-sm text-gray-300">Avg. Detection Time</td>
                      <td className="px-6 py-4 text-center text-sm text-red-400">~8 min</td>
                      <td className="px-6 py-4 text-center text-sm text-green-400">&lt;1 sec</td>
                    </tr>
                    <tr>
                      <td className="px-6 py-4 text-sm text-gray-300">Works During Load-Shedding</td>
                      <td className="px-6 py-4 text-center text-sm text-red-400">No</td>
                      <td className="px-6 py-4 text-center text-sm text-green-400">Yes</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            {/* Visual Comparison Chart */}
            <div>
              <h4 className="text-lg font-semibold text-white mb-4">Detection Comparison</h4>
              <ResponsiveContainer width="100%" height={250}>
                <BarChart data={comparisonData} layout="vertical">
                  <CartesianGrid strokeDasharray="3 3" stroke="#374151" />
                  <XAxis type="number" stroke="#9CA3AF" style={{ fontSize: '12px' }} />
                  <YAxis dataKey="metric" type="category" stroke="#9CA3AF" style={{ fontSize: '12px' }} width={150} />
                  <Tooltip content={<CustomTooltip />} />
                  <Bar dataKey="mcafee" fill="#EF4444" name={trialReport.currentAVName} radius={[0, 4, 4, 0]} />
                  <Bar dataKey="shieldai" fill="#10B981" name="ShieldAI" radius={[0, 4, 4, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>

            {/* Top Threats */}
            <div>
              <h4 className="text-lg font-semibold text-white mb-4">Top Threats Detected</h4>
              <div className="space-y-3">
                {trialReport.topThreats.map((threat, index) => (
                  <div
                    key={index}
                    className="bg-navy-700/50 border border-gray-600/30 rounded-lg p-4 flex items-center justify-between"
                  >
                    <div className="flex-1">
                      <div className="flex items-center gap-3 mb-1">
                        <p className="text-white font-medium">{threat.name}</p>
                        <span className={`inline-flex items-center px-2 py-0.5 rounded text-xs font-medium ${
                          threat.severity === 'critical' ? 'bg-red-500/20 text-red-400 border border-red-500/30' :
                          threat.severity === 'high' ? 'bg-amber-500/20 text-amber-400 border border-amber-500/30' :
                          'bg-yellow-500/20 text-yellow-400 border border-yellow-500/30'
                        }`}>
                          {threat.severity}
                        </span>
                      </div>
                      <div className="w-full bg-gray-700 rounded-full h-2">
                        <div
                          className={`h-2 rounded-full ${
                            threat.severity === 'critical' ? 'bg-red-500' :
                            threat.severity === 'high' ? 'bg-amber-500' : 'bg-yellow-500'
                          }`}
                          style={{ width: `${(threat.count / trialReport.totalThreats) * 100}%` }}
                        />
                      </div>
                    </div>
                    <div className="ml-6 text-right">
                      <p className="text-2xl font-bold text-white">{threat.count}</p>
                      <p className="text-xs text-gray-400">incidents</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* CTA Section */}
            <div className="bg-gradient-to-r from-shield-blue/20 to-blue-600/20 border-2 border-shield-blue/50 rounded-lg p-8 text-center">
              <div className="max-w-2xl mx-auto">
                <h3 className="text-2xl font-bold text-white mb-3">
                  ShieldAI blocked {trialReport.threatsMissedByCurrentAV} threats your current antivirus missed
                </h3>
                <p className="text-gray-300 mb-6">
                  Upgrade to full protection today and keep your business safe from SA-specific cyber threats.
                </p>
                <div className="flex items-center justify-center gap-4">
                  <Link
                    to="/dashboard/pricing"
                    className="px-8 py-3 bg-shield-blue hover:bg-shield-electric text-white rounded-lg font-semibold transition-all shadow-lg shadow-shield-blue/20"
                  >
                    Upgrade to Paid Plan — R2,500/endpoint/month
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Historical Reports */}
        <div className="bg-navy-700 border border-gray-700/50 rounded-lg p-6">
          <h3 className="text-lg font-semibold text-white mb-4">Historical Reports</h3>
          <div className="space-y-3">
            {[
              { name: 'Monthly Summary — March 2026', date: '2026-03-31', type: 'Monthly' },
              { name: 'Monthly Summary — February 2026', date: '2026-02-28', type: 'Monthly' },
              { name: 'Incident Report — Eskom Ransomware Lure', date: '2026-02-12', type: 'Incident' },
            ].map((report, index) => (
              <div
                key={index}
                className="flex items-center justify-between p-4 bg-navy-600 rounded-lg hover:bg-navy-500 transition-colors"
              >
                <div className="flex items-center gap-3">
                  <FileText className="h-5 w-5 text-gray-400" />
                  <div>
                    <p className="text-sm font-medium text-white">{report.name}</p>
                    <p className="text-xs text-gray-400">{report.date}</p>
                  </div>
                </div>
                <div className="flex items-center gap-3">
                  <span className="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-medium bg-gray-700 text-gray-300">
                    {report.type}
                  </span>
                  <button
                    onClick={handleDownloadPDF}
                    className="flex items-center gap-2 px-3 py-1.5 bg-navy-700 hover:bg-navy-600 border border-gray-600 rounded-lg text-sm text-white transition-colors"
                  >
                    <Download className="h-4 w-4" />
                    PDF
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </AppLayout>
  );
}
